// src/components/VideoList.tsx
import { useState, useEffect, useRef } from "react";
import { Button } from "animal-island-ui";
import { MdVideocam, MdMyLocation } from "react-icons/md";
import { useAppContext } from "../context/AppContext";
import { deleteVideo, starVideo } from "../hooks/useMoveVideo";
import "./VideoList.css";

const getFileName = (path: string) => path.split(/[/\\]/).pop() || path;

const formatDuration = (seconds?: number): string => {
  if (seconds === undefined) return "";
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  if (hours > 0)
    return `${hours}:${minutes.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  return `${minutes}:${secs.toString().padStart(2, "0")}`;
};

export default function VideoList() {
  const { filesList, curCrmFile, setCurCrmFile, proxyDir } = useAppContext();
  const [curIndex, setCurIndex] = useState(-1);
  const listContainerRef = useRef<HTMLDivElement | null>(null);
  const curIndexRef = useRef(curIndex);
  const filesListRef = useRef(filesList);
  const curCrmFileRef = useRef(curCrmFile);
  const proxyDirRef = useRef(proxyDir);

  useEffect(() => {
    curIndexRef.current = curIndex;
  }, [curIndex]);
  useEffect(() => {
    filesListRef.current = filesList;
  }, [filesList]);
  useEffect(() => {
    curCrmFileRef.current = curCrmFile;
  }, [curCrmFile]);
  useEffect(() => {
    proxyDirRef.current = proxyDir;
  }, [proxyDir]);

  // Sync curIndex → scroll into view
  useEffect(() => {
    if (curIndex === -1 || !listContainerRef.current) return;
    const items = listContainerRef.current.querySelectorAll(".list-item");
    const item = items[curIndex] as HTMLElement;
    if (item) item.scrollIntoView({ behavior: "smooth", block: "nearest" });
  }, [curIndex]);

  // Sync curIndex → update curCrmFile
  useEffect(() => {
    const file = filesList[curIndex];
    setCurCrmFile(file?.path ?? "");
  }, [curIndex, filesList, setCurCrmFile]);

  // Sync filesList → update curIndex
  useEffect(() => {
    if (!filesList.length) {
      setCurIndex(-1);
      return;
    }
    const found = filesList.findIndex((f) => f.path === curCrmFileRef.current);
    if (found !== -1) {
      setCurIndex(found);
      return;
    }
    const idx = curIndexRef.current;
    if (idx < filesList.length) {
      setCurCrmFile(filesList[idx]?.path ?? "");
    } else {
      setCurIndex(filesList.length - 1);
    }
  }, [filesList, setCurCrmFile]);

  // Keyboard listeners
  useEffect(() => {
    const handler = async (e: KeyboardEvent) => {
      if (e.key === "ArrowUp") {
        setCurIndex((i) => Math.max(i - 1, 0));
      } else if (e.key === "ArrowDown") {
        setCurIndex((i) => Math.min(i + 1, filesListRef.current.length - 1));
      } else if (e.key === "Delete" || e.key === "Backspace") {
        if (curCrmFileRef.current) {
          await deleteVideo(curCrmFileRef.current, proxyDirRef.current);
        }
      } else if (e.key === "Enter") {
        if (curCrmFileRef.current) {
          await starVideo(curCrmFileRef.current, proxyDirRef.current);
        }
      }
    };
    window.addEventListener("keydown", handler);
    return () => window.removeEventListener("keydown", handler);
  }, []);

  const scrollToCurrent = () => {
    if (curIndex === -1 || !listContainerRef.current) return;
    const items = listContainerRef.current.querySelectorAll(".list-item");
    const item = items[curIndex] as HTMLElement;
    if (item) item.scrollIntoView({ behavior: "smooth", block: "center" });
  };

  return (
    <div className="video-list-container">
      <div className="list-header">
        <h3 className="list-title">
          <MdVideocam size={18} />
          视频列表
        </h3>
        <span className="list-count">{filesList.length}</span>
      </div>

      {!filesList.length ? (
        <div className="empty-state">暂无视频文件</div>
      ) : (
        <div ref={listContainerRef} className="list-scroll">
          {filesList.map((file, index) => (
            <div
              key={file.path}
              className={`list-item${curIndex === index ? " active" : ""}`}
              onClick={() => setCurIndex(index)}
            >
              <div className="file-info">
                <div className="file-header">
                  <span className="file-name">{getFileName(file.path)}</span>
                  <div className="file-meta">
                    {file.loading ? (
                      <span className="loading-dot">···</span>
                    ) : file.duration ? (
                      <span className="file-duration">
                        {formatDuration(file.duration)}
                      </span>
                    ) : null}
                  </div>
                </div>
                <span className="file-index">#{index + 1}</span>
              </div>
            </div>
          ))}
        </div>
      )}

      {curIndex !== -1 && (
        <Button
          type="primary"
          className="scroll-btn"
          onClick={scrollToCurrent}
          title="定位到当前选中的视频"
        >
          <MdMyLocation size={16} />
        </Button>
      )}
    </div>
  );
}

// src/components/VideoList.vue
<script setup lang="ts">
import { onMounted, ref, useTemplateRef, watch } from "vue";
import {
  NRadioGroup,
  NRadio,
  NEmpty,
  NText,
  NIcon,
  NBadge,
  NSpin,
  NButton,
} from "naive-ui";
import { VideocamOutline, NavigateOutline } from "@vicons/ionicons5";
import { filesList } from "../hooks/useRawFile";
import { curCrmFile } from "../hooks/useRawFile";
import { deleteVideo, starVideo } from "../hooks/useMoveVideo";

/** 当前选中的文件索引 */
const curIndex = ref(-1);

/** 视频列表容器引用 */
const listContainerRef = useTemplateRef("listContainerRef");

// 提取文件名
const getFileName = (path: string) => {
  const parts = path.split(/[/\\]/);
  return parts[parts.length - 1] || path;
};

// 格式化时长
const formatDuration = (seconds?: number): string => {
  if (seconds === undefined) return "";
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  return `${minutes}:${secs.toString().padStart(2, "0")}`;
};

// 滚动到当前选中的视频
const scrollToCurrentVideo = () => {
  if (curIndex.value === -1 || !listContainerRef.value) return;

  const radioItems = listContainerRef.value.querySelectorAll(".radio-item");
  const currentItem = radioItems[curIndex.value] as HTMLElement;

  if (currentItem) {
    currentItem.scrollIntoView({
      behavior: "smooth",
      block: "center",
    });
  }
};

// 监听当前选中的文件索引
watch(curIndex, (newVal) => {
  const file = filesList.value[newVal];
  curCrmFile.value = file?.path ?? "";
});

// 监听文件列表变化
watch(filesList, (newVal) => {
  // 如果文件列表为空，则设置当前选中的文件索引为 -1
  if (!newVal.length) {
    curIndex.value = -1;
    return;
  }
  // 如果当前选中的文件在文件列表中，则设置当前选中的文件索引为文件列表中的索引
  const newIndex = filesList.value.findIndex(
    (file) => file.path === curCrmFile.value,
  );
  if (newIndex !== -1) {
    curIndex.value = newIndex;
    return;
  }
  // 如果当前选中的文件索引小于文件列表长度，则设置当前选中的文件为文件列表中的文件
  if (curIndex.value < newVal.length) {
    curCrmFile.value = filesList.value[curIndex.value]?.path ?? "";
    return;
  }
  // 如果当前选中的文件索引大于文件列表长度，则设置当前选中的文件索引为最后一个
  curIndex.value = newVal.length - 1;
});

onMounted(() => {
  // 监听方向键上下移动
  window.addEventListener("keydown", (event) => {
    if (event.key === "ArrowUp") {
      curIndex.value = Math.max(curIndex.value - 1, 0);
    } else if (event.key === "ArrowDown") {
      curIndex.value = Math.min(curIndex.value + 1, filesList.value.length - 1);
    }
  });
  // 监听删除键/退格键
  window.addEventListener("keydown", async (event) => {
    if (event.key === "Delete" || event.key === "Backspace") {
      if (!curCrmFile.value) {
        return;
      }
      await deleteVideo(curCrmFile.value);
    }
  });
  // 监听回车键
  window.addEventListener("keydown", async (event) => {
    if (event.key === "Enter") {
      if (!curCrmFile.value) {
        return;
      }
      await starVideo(curCrmFile.value);
    }
  });
});
</script>

<template>
  <div class="video-list-container">
    <div class="list-header">
      <h3 class="list-title">
        <NIcon size="18" :component="VideocamOutline" />
        视频列表
      </h3>
      <NBadge :value="filesList.length" :max="999" type="info" />
    </div>

    <NEmpty
      v-if="!filesList.length"
      description="暂无视频文件"
      class="empty-state"
    />

    <div v-else ref="listContainerRef" class="radio-group">
      <NRadioGroup :value="curIndex" @update:value="(val) => (curIndex = val)">
        <div
          v-for="(file, index) in filesList"
          :key="file.path"
          class="radio-item"
          :class="{ active: curIndex === index }"
        >
          <NRadio :value="index" class="radio-control">
            <div class="file-info">
              <div class="file-header">
                <NText class="file-name">{{ getFileName(file.path) }}</NText>
                <div class="file-meta">
                  <NSpin v-if="file.loading" :size="14" />
                  <NText
                    v-else-if="file.duration"
                    depth="3"
                    class="file-duration"
                  >
                    {{ formatDuration(file.duration) }}
                  </NText>
                </div>
              </div>
              <NText depth="3" class="file-index">#{{ index + 1 }}</NText>
            </div>
          </NRadio>
        </div>
      </NRadioGroup>
    </div>

    <!-- 定位按钮 -->
    <NButton
      v-if="curIndex !== -1"
      circle
      type="primary"
      class="scroll-to-current-btn"
      @click="scrollToCurrentVideo"
      :title="'定位到当前选中的视频'"
    >
      <template #icon>
        <NIcon :component="NavigateOutline" />
      </template>
    </NButton>
  </div>
</template>

<style scoped>
.video-list-container {
  display: flex;
  flex-direction: column;
  height: 100%;
  overflow-x: hidden;
}

.list-header {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  justify-content: space-between;
  padding: 16px;
  background: #fafafa;
  border-bottom: 1px solid #f0f0f0;
}

.list-title {
  display: flex;
  gap: 8px;
  align-items: center;
  margin: 0;
  font-size: 16px;
  font-weight: 600;
  color: #333;
}

.empty-state {
  margin-top: 60px;
}

.radio-group {
  flex-grow: 1;
  height: 0;
  padding: 8px;
  overflow: hidden auto;
}

.radio-item {
  padding: 2px;
  margin-bottom: 4px;
  border-radius: 6px;
  transition: all 0.2s ease;
}

.radio-item:hover {
  background: #f5f5f5;
}

.radio-item.active {
  background: linear-gradient(135deg, #667eea15 0%, #764ba215 100%);
}

.radio-control {
  width: 100%;
  padding: 8px 12px;
}

.file-info {
  display: flex;
  flex-direction: column;
  gap: 6px;
  width: 100%;
  min-width: 0;
}

.file-header {
  display: flex;
  gap: 8px;
  align-items: flex-start;
  justify-content: space-between;
  width: 100%;
}

.file-name {
  flex: 1;
  font-size: 13px;
  line-height: 1.4;
  overflow-wrap: break-word;
}

.file-meta {
  display: flex;
  flex-shrink: 0;
  align-items: center;
  justify-content: flex-end;
  min-width: 50px;
  margin-right: 4px;
}

.file-duration {
  font-family: monospace;
  font-size: 11px;
  font-weight: 500;
  color: #667eea;
}

.file-index {
  font-size: 11px;
}

/* 自定义滚动条 */
.radio-group::-webkit-scrollbar {
  width: 6px;
}

.radio-group::-webkit-scrollbar-track {
  background: transparent;
}

.radio-group::-webkit-scrollbar-thumb {
  background: #d0d0d0;
  border-radius: 3px;
}

.radio-group::-webkit-scrollbar-thumb:hover {
  background: #b0b0b0;
}

/* 定位按钮 */
.scroll-to-current-btn {
  position: absolute;
  right: 16px;
  bottom: 16px;
  z-index: 10;
  box-shadow: 0 4px 12px rgb(102 126 234 / 40%);
}

.scroll-to-current-btn:hover {
  box-shadow: 0 6px 16px rgb(102 126 234 / 50%);
  transform: scale(1.1);
}
</style>
