// src/components/VideoInfo.vue
<script setup lang="ts">
import { ref, watch, computed } from "vue";
import { invoke } from "@tauri-apps/api/core";
import {
  NText,
  NSpin,
  NEmpty,
  NDescriptions,
  NDescriptionsItem,
  NTag,
} from "naive-ui";
import { updateFileDuration } from "../hooks/useRawFile";

const props = defineProps<{
  videoPath: string;
}>();

interface VideoInfo {
  duration: number;
  width: number;
  height: number;
  codec: string;
  bit_rate: string;
  frame_rate: string;
  audio_codec: string | null;
  audio_channels: number | null;
  file_size: number;
  modified_time: number;
}

const videoInfo = ref<VideoInfo | null>(null);
const errMsg = ref<string | null>(null);
const loading = ref(false);

// 格式化时长
const formatDuration = (seconds: number) => {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);

  if (hours > 0) {
    return `${hours}:${minutes.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  }
  return `${minutes}:${secs.toString().padStart(2, "0")}`;
};

// 格式化比特率
const formatBitrate = (bitrate: string) => {
  const rate = parseInt(bitrate);
  if (rate > 1000000) {
    return `${(rate / 1000000).toFixed(2)} Mbps`;
  }
  return `${(rate / 1000).toFixed(2)} Kbps`;
};

// 格式化帧率
const formatFrameRate = (frameRate: string) => {
  // 如果是分数格式 (如 "60/1")
  if (frameRate.includes("/")) {
    const [numerator, denominator] = frameRate.split("/").map(Number);
    if (denominator && denominator !== 0) {
      const fps = numerator / denominator;
      return fps % 1 === 0 ? fps.toString() : fps.toFixed(2);
    }
  }
  return frameRate;
};

// 格式化文件大小
const formatFileSize = (bytes: number) => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  if (bytes < 1024 * 1024 * 1024)
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
};

// 格式化修改时间
const formatModifiedTime = (timestamp: number) => {
  const date = new Date(timestamp * 1000);
  return date.toLocaleString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });
};

// 获取文件名
const fileName = computed(() => {
  if (!props.videoPath) return "";
  const parts = props.videoPath.split(/[/\\]/);
  return parts[parts.length - 1] || props.videoPath;
});

watch(
  () => props.videoPath,
  async (newVal) => {
    if (!newVal) {
      videoInfo.value = null;
      errMsg.value = null;
      return;
    }

    loading.value = true;
    try {
      const info: VideoInfo = await invoke("get_video_info", {
        videoPath: newVal,
      });
      videoInfo.value = info;
      errMsg.value = null;

      // 更新时长缓存到列表
      updateFileDuration(newVal);
    } catch (error) {
      errMsg.value = error as string;
      videoInfo.value = null;
      console.error(error);
    } finally {
      loading.value = false;
    }
  },
  { immediate: true },
);
</script>

<template>
  <div class="video-info-container">
    <NEmpty v-if="!videoPath" description="未选择文件" size="small" />

    <NSpin v-else-if="loading" size="small" class="loading-spinner">
      <template #description>加载中...</template>
    </NSpin>

    <div v-else-if="errMsg" class="error-message">
      <NText type="error">{{ errMsg }}</NText>
    </div>

    <div v-else-if="videoInfo" class="info-content">
      <NText depth="3" class="file-path" :title="videoPath">
        {{ fileName }}
      </NText>

      <NDescriptions
        :column="1"
        size="small"
        label-placement="left"
        class="info-descriptions"
      >
        <NDescriptionsItem label="分辨率">
          <NTag size="small" type="info">
            {{ videoInfo.width }} × {{ videoInfo.height }}
          </NTag>
        </NDescriptionsItem>

        <NDescriptionsItem label="文件大小">
          {{ formatFileSize(videoInfo.file_size) }}
        </NDescriptionsItem>

        <NDescriptionsItem label="修改时间">
          {{ formatModifiedTime(videoInfo.modified_time) }}
        </NDescriptionsItem>

        <NDescriptionsItem label="时长">
          {{ formatDuration(videoInfo.duration) }}
        </NDescriptionsItem>

        <NDescriptionsItem label="视频编码">
          <NTag size="small" type="success">{{ videoInfo.codec }}</NTag>
        </NDescriptionsItem>

        <NDescriptionsItem label="比特率">
          {{ formatBitrate(videoInfo.bit_rate) }}
        </NDescriptionsItem>

        <NDescriptionsItem label="帧率">
          {{ formatFrameRate(videoInfo.frame_rate) }} fps
        </NDescriptionsItem>

        <NDescriptionsItem v-if="videoInfo.audio_codec" label="音频编码">
          <NTag size="small" type="warning">{{ videoInfo.audio_codec }}</NTag>
        </NDescriptionsItem>

        <NDescriptionsItem v-if="videoInfo.audio_channels" label="音频声道">
          {{ videoInfo.audio_channels }} 声道
        </NDescriptionsItem>
      </NDescriptions>
    </div>
  </div>
</template>

<style scoped>
.video-info-container {
  min-height: 200px;
}

.loading-spinner {
  display: flex;
  align-items: center;
  justify-content: center;
  min-height: 200px;
}

.error-message {
  padding: 16px;
  text-align: center;
}

.info-content {
  padding: 8px 0;
}

.file-path {
  display: block;
  padding: 8px;
  margin-bottom: 12px;
  overflow: hidden;
  text-overflow: ellipsis;
  font-family: inherit;
  font-size: 12px;
  white-space: nowrap;
  background: #f5f5f5;
  border-radius: 4px;
}

.info-descriptions {
  margin-top: 8px;
}

:deep(.n-descriptions-table-wrapper) {
  padding: 0;
}

/* stylelint-disable-next-line selector-class-pattern */
:deep(.n-descriptions .n-descriptions-table-content__label) {
  font-weight: 500;
  color: #666;
}
</style>

// src/components/VideoInfo.tsx
import { useState, useEffect } from "react";
import { invoke } from "@tauri-apps/api/core";
import { useAppContext } from "../context/AppContext";
import "./VideoInfo.css";

interface VideoInfo {
  duration: number;
  width: number;
  height: number;
  codec: string;
  bit_rate: string;
  frame_rate: string;
  audio_codec: string | null;
  audio_channels: number | null;
  file_size: number;
  modified_time: number;
}

const formatDuration = (seconds: number) => {
  const hours = Math.floor(seconds / 3600);
  const minutes = Math.floor((seconds % 3600) / 60);
  const secs = Math.floor(seconds % 60);
  if (hours > 0)
    return `${hours}:${minutes.toString().padStart(2, "0")}:${secs.toString().padStart(2, "0")}`;
  return `${minutes}:${secs.toString().padStart(2, "0")}`;
};

const formatBitrate = (bitrate: string) => {
  const rate = parseInt(bitrate);
  if (rate > 1000000) return `${(rate / 1000000).toFixed(2)} Mbps`;
  return `${(rate / 1000).toFixed(2)} Kbps`;
};

const formatFrameRate = (frameRate: string) => {
  if (frameRate.includes("/")) {
    const [n, d] = frameRate.split("/").map(Number);
    if (d) {
      const fps = n / d;
      return fps % 1 === 0 ? fps.toString() : fps.toFixed(2);
    }
  }
  return frameRate;
};

const formatFileSize = (bytes: number) => {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(2)} KB`;
  if (bytes < 1024 * 1024 * 1024)
    return `${(bytes / (1024 * 1024)).toFixed(2)} MB`;
  return `${(bytes / (1024 * 1024 * 1024)).toFixed(2)} GB`;
};

const formatModifiedTime = (timestamp: number) => {
  return new Date(timestamp * 1000).toLocaleString("zh-CN", {
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
    hour: "2-digit",
    minute: "2-digit",
    second: "2-digit",
    hour12: false,
  });
};

export default function VideoInfo({ videoPath }: { videoPath: string }) {
  const { updateFileDuration } = useAppContext();
  const [videoInfo, setVideoInfo] = useState<VideoInfo | null>(null);
  const [errMsg, setErrMsg] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);

  const fileName = videoPath ? videoPath.split(/[/\\]/).pop() || videoPath : "";

  useEffect(() => {
    if (!videoPath) {
      setVideoInfo(null);
      setErrMsg(null);
      return;
    }
    setLoading(true);
    invoke<VideoInfo>("get_video_info", { videoPath })
      .then((info) => {
        setVideoInfo(info);
        setErrMsg(null);
        updateFileDuration(videoPath);
      })
      .catch((err) => {
        setErrMsg(err as string);
        setVideoInfo(null);
      })
      .finally(() => setLoading(false));
  }, [videoPath, updateFileDuration]);

  if (!videoPath) {
    return (
      <div className="video-info-empty">
        <span>未选择文件</span>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="video-info-loading">
        <span>加载中...</span>
      </div>
    );
  }

  if (errMsg) {
    return (
      <div className="video-info-error">
        <span>{errMsg}</span>
      </div>
    );
  }

  if (!videoInfo) return null;

  return (
    <div className="video-info-content">
      <span className="file-path" title={videoPath}>
        {fileName}
      </span>
      <dl className="info-list">
        <div className="info-row">
          <dt>分辨率</dt>
          <dd>
            <span className="info-tag">
              {videoInfo.width} × {videoInfo.height}
            </span>
          </dd>
        </div>
        <div className="info-row">
          <dt>文件大小</dt>
          <dd>{formatFileSize(videoInfo.file_size)}</dd>
        </div>
        <div className="info-row">
          <dt>修改时间</dt>
          <dd>{formatModifiedTime(videoInfo.modified_time)}</dd>
        </div>
        <div className="info-row">
          <dt>时长</dt>
          <dd>{formatDuration(videoInfo.duration)}</dd>
        </div>
        <div className="info-row">
          <dt>视频编码</dt>
          <dd>
            <span className="info-tag info-tag-green">{videoInfo.codec}</span>
          </dd>
        </div>
        <div className="info-row">
          <dt>比特率</dt>
          <dd>{formatBitrate(videoInfo.bit_rate)}</dd>
        </div>
        <div className="info-row">
          <dt>帧率</dt>
          <dd>{formatFrameRate(videoInfo.frame_rate)} fps</dd>
        </div>
        {videoInfo.audio_codec && (
          <div className="info-row">
            <dt>音频编码</dt>
            <dd>
              <span className="info-tag info-tag-orange">
                {videoInfo.audio_codec}
              </span>
            </dd>
          </div>
        )}
        {videoInfo.audio_channels && (
          <div className="info-row">
            <dt>音频声道</dt>
            <dd>{videoInfo.audio_channels} 声道</dd>
          </div>
        )}
      </dl>
    </div>
  );
}
